version: '3.8'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./src/db:/docker-entrypoint-initdb.d
    env_file: ./.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 3306:3306
      
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=$JWT_SECRET
